### ISSUE TITLE
QXmpp 1.1

### ISSUE THREAD

**Issue by lnjX** [qxmpp-project/qxmpp#219]
ToDo:
- [x] Finish HTTP File Upload (#129, #203)
- [x] Revert MIX Roster extensions: there were talks on the mailing list that this is done using a PEP node in the future and I would like to not make this official API for now. (#223)
- [x] Refactor media element (#222)
- [x] Fix deprecation warnings caused by #214 (#225)
- [x] Add `\since` to all new methods / classes
- [ ] Update changelog

After release:
- [ ] Merge #210
- [ ] Update README: Qt 5.7 required
- [ ] Replace `Q_ENUMS` by `Q_ENUM` (added in Qt 5.5)
- [ ] Remove Qt < 5.7 compatibility code

Any other ToDos for the next release?

**Comment by lnjX** [comment]
@tehnick @0xd34df00d Ready for QXmpp 1.1?

**Comment by tehnick** [comment]
Yes. I may update packages in PPA even today.
As for Debian repos, it will be not so soon...

**Comment by lnjX** [comment]
@jlaine Could you update the documentation on doc.qxmpp.org?

**Comment by 0xd34df00d** [comment]
Late yes from me just for the record, lol. Will update the gentoo repos.

**Comment by lnjX** [comment]
@tehnick Thanks for uploading to debian :)
